language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://test.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "XGtQ4BDNHxxtIPjBCERQLZLmN0uzcUQ1OpAiaAOOKE4hJ/YE5yfwvWX9Ti66WMs6qGjGwSy5L8APBF491cErt64c9XAaOOQe4UdmpmNnzc9TCpG6IavzR08rKLX+tIR/5bfW6c1j3l+aUv70P7t2X3wW7fA5xrql+ewENugemIQpkmWfA6vG4Unt/Har3TGLSlD1gFAetgBUHiONwqWBEAwRIa92H0Cuu0JqW/gw1OubhksPB4LRU6Ga3zIxkQUoPrHO1+/FaoTCjkevvwYwfLiNw33VzQRzBGqhIj+rkr0m264RzAPumQiY2ovrKDGZ5RYis2L1PujRtndwYyAO4LeC1UAQ1fYvBuOLeibiUzIypkZx4cOEnSu5lc6G9MVSqqP7eR1/KZ5TdGphz/iJqXKB3bd3Ld2tHNofHVEROtk9x4wMtgCGCxvgDLvbPXIFTe/s8OFMvWPoMBtSXNS0fAkGqY2hKR236/XLDMAZ6Gk9zfYyp+PAzxvfhdZ+wYmhBLJ+SmSo9bxSoQ0rR0cXvU5aJANns47QnbixeJBqX7/QReAB/IIyCrPlJyWSUhZft0UDuaDaCazbaSw9daChbHCScYe/B6vsnGEuNuV/nAWrXxBifY/dDepwAmWQ3D/U/yEb0xpxKVOQ988x92MJBG/dpdm3BtNVUTp5CNphzpA="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
