language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://test.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "l+Y1hHBgKqH44TcV1EwbU9mxSYkC3JAjh9jNU9n82ZnlHEdUO/ive5hfVUjzCLZs/a/VkHWbbdLM3LwNxIS+qVuFE9KLCk8QUlJ6xU0k7OA0kgOblAGx5URPrknIsdSq8X2rF6CQRy6n7348wyTMyZyaR2EI7QnlvYUwRrcvzmttKRIhseWUGI9k77wAzINFpe8wqtSrEgD0LivB+uYqkvyrdd4c50Tp0nbUAPdTnkLcp74In/aBrSsiTd9kV2crsu+2ionWNC1ZTrLwZDjCtUDnDEO7GEqJ8wBJ4eXLe0JYaAqNq/HgDu+KC+dfIJ7Vk6WiM+gkIhkcNziRm+Qx9FwWp8P1EHx1mcVPSpI7latlVgfvhYXbVbubVdt4kveIvMC+CeYmufNZpAngJiK+6E9OctWLyk3AjvvIcPQPzM1iblHdHK92DTUmp0vEXbCXTKrb6B7ZHMQFjj9tE2jO/NATqkrkQewaHkdNV5rtTtt0PYDO3h9EtePDkRyaA2rosg7eypgHxJ3g1Oj73GrO6NSMvXi+1+JmKoFzXF7qvnYuM6OxnrrXtXajEuKGlZfaRHUkH9+HVaY+cFuyE5qBO7krPtxlQY5pkXMedMb+qw0h3FN3K7CL+yz9NMmiug3SPQPcVQRpyp9P6SjtqztoJbCFT6qgyFbvfWXxxUwNS8s="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
