language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://ayush1.pact.dius.com.au/
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "KOj3WOt6HOLbKGa/SkR3Tt92+WhpGBMqVPc87to6FzraDEe4liKmE9q+4uWxkz7IZ+CquBOU9d4yRX6smLSTmqYyXBQJ+fRr0iaCRSi4hR4nzlFC/i/MytnqldygCQrXmqVRrtmjgZlftF+BEvOLaXoV/+XzJT1ygZ4xYwvHizCzmgXgk3TEpHZ7q5NYYXb8+s98MuX97Piag350iBGM+GHZbjISSxyeOXwKL5tXw0Plvn4fTxmWzn6ZD/k1f5HcGrFMVFtv0dKsVedhsdpq9FDaLn+zszBBTlD8265YLeQVsaL0Ws/OJqEQM9+pkQX2gkJoPW/GJuxmVKShQGX9l6UigXX8WRx4glQt37UJYOgVsHFtGEy6G3lnR7QUuA4OiMMkzabHUH+GVWkanXczRCmAPo7c4KFGVQS9CT14XC2Z7BH/7hn0kpXHygzHAShn2zBtBzSHTXZYZvfBGonItcyGnvHhcYsGkiFhg/fa2E3zGoOo4+DGEV5yZ2xzqjhZaypSCtcU5ta/CW3loxIuRG/7NO8dTG4iclBsVLeXOi9C2uOghtXoR+B6OdXt+zMSUwHoOIgrO4j5scOLBdq4SdN7icuhdh1GggDHeEVoaUqJkXQP7VhFFpTWYxDxbPLQbZfnV8zRTQ7bUFnKM0L2wy8xpoT/mNQQui6UW+7O6J4="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
